Added More Entitybag implementations
Quillraven/Fleks pull request #157
Opened 2024-09-05 20:30 UTC by AnderWoche

How i can link this to a Issue?

2024-09-05 20:31 UTC, AnderWoche commented
I made MutableEntityBag to an interface, and two implementations for it.

2024-09-05 20:34 UTC, AnderWoche commented
Ref #156

2024-09-06 05:04 UTC, Quillraven commented
thank you for the contribution - looks good to me! I wonder if the list version can be simplified with Kotlin's delegation? Maybe you can write:

```kotlin
class ListMutableEntityBag(
    @PublishedApi
    internal val list: MutableList<Entity>
) : MutableEntityBag by list {
```

But I am not sure if the delegation mechanism is smart enough to detect that the methods are the same. I guess they'd need a common interface and I am not sure if there is one ;)

2024-09-06 05:06 UTC, Quillraven commented on src/commonMain/kotlin/com/github/quillraven/fleks/collection/ListMutableEntityBag.kt
> +    internal val list: MutableList<Entity>
Please rename it to `values` to be consistent with the other bag implementation.

2024-09-06 05:09 UTC, Quillraven requested changes
Please add a test class for the list implementation as well. Most likely you can copy&paste the `ArrayEntityBagTest` file and just change the bag to the list version.

2024-09-06 12:16 UTC, AnderWoche commented
![image](https://github.com/user-attachments/assets/a34a872d-1b1d-4cd3-baee-afc7d5760c2b)

by not working

2024-09-06 12:44 UTC, AnderWoche commented on src/commonTest/kotlin/com/github/quillraven/fleks/collection/ListMutableEntityBagTest.kt
> +    private fun arrayBagOf(entity: Entity) = ArrayMutableEntityBag(1).apply {
Many functions from the ListMutableEntityBag return an ArrayMutableEntityBag, which is intentional, so I have adapted the tests for it

2024-09-06 12:46 UTC, AnderWoche commented on src/commonTest/kotlin/com/github/quillraven/fleks/collection/ListMutableEntityBagTest.kt
> +    private fun arrayBagOf(entity: Entity) = ArrayMutableEntityBag(1).apply {
With the MutableList it is impossible to get the capacity variable so I have removed the tests.

2024-09-06 12:48 UTC, AnderWoche commented
In the List implementation i habe this one:

```kotlin
 /**
     * Resizes the bag to fit in the given [capacity] of [entities][Entity] if necessary.
     */
    override fun ensureCapacity(capacity: Int) {
        throw NotImplementedError("Not Supported")
    }

    /**
     * Resets [size] to zero, clears any [entity][Entity] of the bag, and if necessary,
     * resizes the bag to be able to fit the given [capacity] of [entities][Entity].
     */
    override fun clearEnsuringCapacity(capacity: Int) {
        throw NotImplementedError("Not Supported")
    }
```

yout are fine with this?

2024-09-06 14:43 UTC, Quillraven commented
I was not aware of a NotImplementedError but imo it makes sense if the class does not have that.

Of course one would ask why the interface has it but the implementation doesn't. That is for sure not clean. Can we maybe remove it from the interface and just use the array implementation internally in Fleks? Need to have a look when I am at a computer again 😅

Out of curiosity: how do you actually use the list implementation? I mean how do you get entities in it?

2024-09-06 16:55 UTC, AnderWoche commented
My usecase is this:

```kotlin
class ChildrenComponent : Component<ChildrenComponent> {

    val children = ListMutableEntityBag(ArrayList(8)) // on remove the order stays the same thats for me important.

    override fun World.onRemove(entity: Entity) {
        children.forEach { child ->
            child.configure {
                it -= ParentComponent
            }
        }
    }

    override fun type() = ChildrenComponent

    companion object : ComponentType<ChildrenComponent>()
}
```

2024-09-06 17:13 UTC, AnderWoche commented
!!!! I have a new idea:

Why does the MutableEntityBag have its own interface?

couldn't we just replace the <EntityBag> interface with the <MutableList> interface that comes from kotlin?

2024-09-06 17:19 UTC, Quillraven commented
If there is an interface that contains all those methods then sure, would be better to use it. 

I still don't get in your example why you are not using a normal list? What is the advantage of using an entitybag which is actually a list in the background? 😅

2024-09-06 17:28 UTC, AnderWoche commented
![Idea](https://github.com/user-attachments/assets/e50c94af-34db-468e-9f8b-ce9843cca321)

2024-09-06 17:36 UTC, AnderWoche commented
I have just looked it up right now, I wouldn't need it. (because I have reprogrammed it again) 
but before it was like this:

```kotlin
    private fun validate(parent: Entity?, children: EntityBag) {
        // validatre children
        children.forEach { newParent ->
            val newChildren = newParent.getOrNull(ChildrenComponent)?.children
            if (newChildren != null) {
                validate(newParent, newChildren)
            }
        }
    }
```

and i wantet to start the method like:

```kotlin
    override fun onTick() {
        super.onTick()

        validate(null, family.entities) // The family.entities has forced me to use the interface everywhere
    }
```

2024-09-06 17:38 UTC, AnderWoche commented
The Problem was that the fast MutableEntityBag implementation had to sorting if you habe these entities:
1
2
3

and you remove 1

the oder was:

3
2

and not:

2
3

thats why i needed a "sorted" entity bag

2024-09-06 17:44 UTC, Quillraven commented
Ah okay now I get it. Well, a bag is a special data structure which doesn't care about order and is therefore a very fast and efficient way to add/remove elements. It is basically a dynamically growing array without the overhead of other data structures.

2024-09-06 17:51 UTC, AnderWoche commented
I will test if we can use the collection interface because e.g. all extra functions like .all {} would be included automatically

2024-09-06 17:56 UTC, AnderWoche commented
Okay i have a new idea:

Maybe it is enough to implement only the Iterable interace

2024-09-08 22:47 UTC, AnderWoche commented
Ok pls take a look at this.
if its okay i going to write some tests

also take a look at the .forEach funktion now there will be the iterator i think it should be fast anyway couse the iterator is reused.
But can you do a performance test for safety?

2024-09-08 22:51 UTC, AnderWoche commented
Take a Look at the _EntityBag.kt

The normal extension functions often return a list instead of an EntityBag. where you originally returned an EntityBag, I have added the function.

2024-09-08 23:19 UTC, Quillraven commented
Thank you for your effort. I am currently on holiday for three weeks and don't have access to a computer, sorry.

I will have a look when I am back.

Regarding performance test: there is a Gradle task called jvmBenchmarks if I remember correctly. That should work for you as well.

There is also a manual.kt file where you can run benchmarks. However, you should run them a few times and take an average value.

For the Gradle benchmarks you don't need to do that but they also run for a longer time.

2024-09-15 01:28 UTC, Quillraven commented
@AnderWoche: I just had a look now and that looks like way too many changes for what we are trying to achieve here. Also, the iterator seems to be limited to only two nested iterations? In general, it does not look like a clean solution imo.

I do like the Collection interface for the EntityBag. I will have a look at that when I am back from my holiday and have more time.

In the meanwhile - you already solved your initial problem in a different way, right? Or is there an easier "quick win" that we can introduce to help you?

2024-10-01 09:59 UTC, Quillraven commented
Hi,

I had now some time and since you already solved your initial problem in a different way, I will close this PR.

The reason why I don't want to take over those changes are:
- the bag datastructure has no order. Adding an implementation that keeps the order is therefore not ideal in my opinion. A better approach is to use your own data structure and add the entities to it the way you need it.
- the `Collection` interface comes with an iterator which is in my opinion unnecessary. I don't see any use-case where an iterator is needed since we already have `forEach` implementations.
- renaming `MutableEntityBag` to something else is a breaking change, which we also should try to avoid.


However, I still want to thank you for your idea and time. I learned a few things because of that!

2024-10-01 09:59 UTC, closed without merging